---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Blog Post
- type: directory
  path: exampleSite/content/blog
  label: Post
  create: documents
  match: "**/*"
  new_doc_ext: app
  templates:
  - post
- type: heading
  label: Portfolio
- type: directory
  path: exampleSite/content/portfolio
  label: Portfolio
  create: documents
  match: "**/*"
- type: heading
  label: Configuration
- type: directory
  path: exampleSite
  label: Configuration
  create: all
  match: "*.toml"
  new_doc_ext: toml
- type: directory
  path: exampleSite/data
  label: Homepage
  create: all
  match: "**/*"
upload_dir: exampleSite/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.58.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public && cd exampleSite && hugo --gc --themesDir ../..
version: 0.58.2
